---

kube_version: v1.8.3
token: b0f7b8.8d1767876297d85c

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

service_subnet: 10.96.0
service_cidr: "{{ service_subnet }}.0/12"
dns_name: cluster.local
dns_ip: "{{ service_subnet }}.10"

# Network implementation('flannel', 'calico')
network: calico
pod_network_cidr: 10.244.0.0/16
cni_opts: interface=eth1 # flannel: --iface=eth1, calico: interface=eth1

# A list of insecure registrys you might need to define
insecure_registrys:
# - "gcr.io"
