---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: helm

- name: "Check if Helm is installed"
  shell: command -v helm >/dev/null 2>&1
  register: helm_exists
  ignore_errors: yes
  tags: helm

- name: "Install Helm"
  block:
    - name: "Get Helm installer"
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get
        dest: "{{ tmp_dir }}/get_helm.sh"
        mode: 0755
  
    - name: "Run the installer"
      shell: "{{ tmp_dir }}/get_helm.sh"

  when: helm_exists.rc > 0
  tags: helm

- name: "Copy yaml file"
  copy:
    src: "rbac-config.yml"
    dest: "{{ tmp_dir }}/rbac-config.yml"
    mode: 0644
  tags: helm

- name: "RBAC configuration"
  shell: "kubectl apply -f {{ tmp_dir }}/rbac-config.yml"
  tags: helm

- name: "Init Helm"
  shell: "helm init --service-account tiller"
  tags: helm

- name: "Update Helm repo"
  shell: "helm repo update"
  tags: helm

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: helm
