---

- name: Reset Kubernetes component
  shell: "kubeadm reset"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster|succeeded
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ token }} \
                 {{ groups['master'][0] }}:6443
  register: join_cluster

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
